version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aura-db
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
      ignoreApplicationStopFailures: true
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
